name: Update GitHub Metrics

on:
  schedule:
    - cron: "0 1 * * *"  # update setiap hari jam 08:00 WIB
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: neushepa
          template: classic
          base: header, repositories, activity, metadata
          config_timezone: Asia/Jakarta
          output_action: commit
          committer_branch: main
          committer_message: "chore: update GitHub metrics"
          filename: metrics.svg

          # ======================
          # âœ… THEME (gunakan preset)
          # ======================
          config_presets: classic
          config_display: columns

          # ======================
          # ðŸ§¾ WAKATIME
          # ======================
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_user: neushepa
          plugin_wakatime_sections: time, languages, editors, projects, os
          plugin_wakatime_repositories_visibility: all
          plugin_wakatime_days: 365
          plugin_wakatime_charts: yes

          # ======================
          # âœ¨ EXTRA VISUAL
          # ======================
          config_twemoji: yes
          config_padding: 16,16
          plugin_languages: no
          plugin_lines: no
