name: Generate Metrics

on:
  schedule:
    - cron: "0 0 * * *" # update setiap hari
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # âœ¨ Basic setup
          user: neushepa
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          config_display: columns

          # ğŸ† Achievements + grade circle
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_threshold: B
          plugin_achievements_secrets: no

          # ğŸ“Š Languages bar
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 12

          # â±ï¸ WakaTime integration
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, languages
          plugin_wakatime_user: neushepa
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}

          # ğŸ¨ Style
          plugin_languages_colors: github
          plugin_languages_indepth: no
          plugin_languages_ignored: html, css
          plugin_achievements_ignored: explorer, stargazer
          config_padding: 5%
          config_order: languages, wakatime, achievements
          filename: metrics.svg
