name: Update GitHub README

on:
  schedule:
    - cron: "0 */12 * * *" # update setiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Clean README
        run: |
          # Hapus baris Auto Update dan Last updated jika ada
          sed -i '/## Auto Update/d' README.md
          sed -i '/Last updated:/d' README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: clean README"
          git push
